name: Test
on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        redis-version: [7]

    runs-on: ${{ matrix.platform }}

    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf \
          libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-0 webkit2gtk-4.1-dev

      - name: Install frontend dependencies
        run: pnpm install

      - name: Run frontend tests
        run: pnpm test:coverage

      - name: Upload frontend coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
          flags: frontend

      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo test

      - name: Upload Rust coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./src-tauri/target/coverage/*.json
          fail_ci_if_error: true
          flags: backend
